import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import "./styles/neomorphs.css";
import Header from "@/components/header";
import ThemeProvider from "@/components/theme-provider";
import { ThemeToggle } from "@/components/ThemeToggle";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Sayit Wiki",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen dotted wooden`}
            >
                <ThemeProvider>
                    <Header />
                    {children}
                    <ThemeToggle />
                </ThemeProvider>
            </body>
        </html>
    )
}
