import type { Metadata } from "next";
import { Finger_Paint } from "next/font/google";
import "./styles/globals.css";
import "./styles/fonts.css";
import "./styles/neomorphs.css";
import Header from "@/components/header";
import ThemeProvider from "@/components/theme-provider";
import { ThemeToggle } from "@/components/ThemeToggle";
import { Toaster } from "@/components/ui/sonner";

const fingerPaint = Finger_Paint({
    variable: "--font-finger-paint",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Sayit Wiki",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${fingerPaint.variable} antialiased min-h-[100dvh] dotted wooden`}
            >
                <Toaster />
                <ThemeProvider>
                    <Header />
                    {children}
                    <ThemeToggle />
                </ThemeProvider>
            </body>
        </html>
    )
}
